//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNMENT_STUDENT
    {
        public decimal ID { get; set; }
        public System.DateTime ASSIGNEDDATE { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public string GRADE { get; set; }
        public decimal ASSIGNMENT_ASSIGNMENTID { get; set; }
        public decimal STUDENT_STUDENTID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
