//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.STUDENTs = new HashSet<STUDENT>();
        }
    
        public decimal DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string EMAIL { get; set; }
        public string EXTENSION { get; set; }
    
        public virtual ICollection<STUDENT> STUDENTs { get; set; }
    }
}
