//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASSIGNMENT> ASSIGNMENTs { get; set; }
        public DbSet<ASSIGNMENT_STUDENT> ASSIGNMENT_STUDENT { get; set; }
        public DbSet<ASSIGNMENT_TYPE> ASSIGNMENT_TYPE { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<PAYMENT> PAYMENTs { get; set; }
        public DbSet<STUDENT> STUDENTs { get; set; }
        public DbSet<STUDENT_MODULE> STUDENT_MODULE { get; set; }
        public DbSet<STUDENT_TO_TEACHER> STUDENT_TO_TEACHER { get; set; }
        public DbSet<TEACHER> TEACHERs { get; set; }
        public DbSet<TEACHER_DEPARTMENT> TEACHER_DEPARTMENT { get; set; }
        public DbSet<TEACHER_MODULE> TEACHER_MODULE { get; set; }
        public DbSet<STUDENT_MODULE_PAYMENT> STUDENT_MODULE_PAYMENT { get; set; }
        public DbSet<MODULE> MODULEs { get; set; }
    }
}
