//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_MODULE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ATTENDANCE { get; set; }
        public string MODULE_MODULECODE { get; set; }
        public decimal STUDENT_STUDENTID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual MODULE MODULE { get; set; }
    }
}
