//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TO_TEACHER
    {
        public decimal ID { get; set; }
        public System.DateTime PROMOTEDDATE { get; set; }
        public decimal STUDENT_STUDENTID { get; set; }
        public decimal TEACHER_TEACHERID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
