//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.ASSIGNMENT_STUDENT = new HashSet<ASSIGNMENT_STUDENT>();
            this.STUDENT_MODULE = new HashSet<STUDENT_MODULE>();
            this.STUDENT_TO_TEACHER = new HashSet<STUDENT_TO_TEACHER>();
            this.STUDENT_MODULE_PAYMENT = new HashSet<STUDENT_MODULE_PAYMENT>();
        }
    
        public decimal STUDENTID { get; set; }
        public string STUDENTNAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public decimal DEPARTMENT_DEPARTMENTID { get; set; }
    
        public virtual ICollection<ASSIGNMENT_STUDENT> ASSIGNMENT_STUDENT { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<STUDENT_MODULE> STUDENT_MODULE { get; set; }
        public virtual ICollection<STUDENT_TO_TEACHER> STUDENT_TO_TEACHER { get; set; }
        public virtual ICollection<STUDENT_MODULE_PAYMENT> STUDENT_MODULE_PAYMENT { get; set; }
    }
}
