//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berklee.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_MODULE
    {
        public decimal ID { get; set; }
        public string MODULE_MODULECODE { get; set; }
        public decimal TEACHER_TEACHERID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
        public virtual MODULE MODULE { get; set; }
    }
}
